### ISSUE TITLE
Carousels

### ISSUE THREAD

**Issue by michaelspellacy** [tmpworldwide/tmpworldwide.github.io#17]
Ah, the carousel. The user interface we love to hate. I want to open up a discussion in creating a primer for designers/developers on when they should and should not use a carousel. I'll make a couple of points below and you guys can add on (or counter-point) and maybe we can come up with de facto document for handling carousels in our neck of the woods. 

For me it usually comes down to one thing: Content. I am more worried about hiding content than i am about performance because performance can generally be handled well if we take the time to focus on executing it properly. There are levels of content we should consider before we make choice to use a carousel interface.

**Importance:** How important is this content? (Well, all content is, but we'll prioritize) Given the nature of users in not engaging with content presented deeper down within a carousel, is it wise to use one or should alternative ways to arrange this content be thought through. 

**Content:** What type of content would lend itself well to a carousel? Maybe we can have a list of interface types. A photo gallery or banners are possible if executed properly. A section touting one's accolades...probably not. 

**Performance:** Will this carousel harm my page load and thereby the user experience (and the brand)? If one must be used, can it be constructed in a way that is friendly to performance?

**Comment by JakeRuef** [comment]
Oh boy, this is one i have to talk about a lot. Like Spell, content visiability is ususally what I go with when warning people about the caraousel. I think it could be a great solution to certain pieces of content that are less important to the solution  on slides 2, 3, 4, etc. 

Below I thought i'd drop a couple of the links i like to share. The main one being the study of Notre Dames homepage where they found that about 80% of visitors didnt see any of the slides besides the first one. At the "event apart" conference Luke W, mentioned that those little dots or numbers indicating the slides is not very effective. He had used Amazon as a case study which he explained that with all the different and larg amount of things they sell, some sort of a slider solution was needed. So they went with the sldier area (about 75% of the width) and a prieview section (about 25%) of the width that gave button-like callouts and teasers so that a user would notice and want to click on them. These button-teasers then rotated the slider area to that product.  But before this gets any longer...here's the links:

http://bradfrost.com/blog/post/carousels/

http://erikrunyon.com/2013/01/carousel-stats/

shouldiuseacarousel.com

**Comment by michaelspellacy** [comment]
I think TMP is fairly judicious in how it uses carousels these days, which is kind of cool. Closing.
