### ISSUE TITLE
SCSS organization: Different Strokes for Different Folks

### ISSUE THREAD

**Issue by sbkates** [tmpworldwide/tmpworldwide.github.io#21]
In the meeting today, the topic of organizing SCSS 'wrong' came up, where it was stated that media queries should be put inside each individual element, instead of grouped all in the same place for each section of the page. I guess the speaker believed that things are 'more organized' this way. 

I noticed that this is the way the default SCSS is laid out in the 2.0 system, and I re-arrange it every time, because it feels _less_ organized to me than grouping elements inside break points. 

When I am imagining a certain section of a site in my head, I don't picture it in terms of "this element changes this way on screen size change, this element changes this other way on screen size change, this other element changes this way on screen size change." I picture it in terms of "This section of the page looks like this on mobile. On screen size change, this entire section looks like that." It feels more like I am hunting and pecking for what to modify when I am working with code where the media queries are scattered throughout elements, than it does when it's all grouped together underneath the media queries. 

Plus, when I develop, I develop for one screen size at a time. First I write all of my code for mobile. Then I make the screen size bigger, and write it for tablet, then I write the code for desktop. It just makes sense to me to copy and paste what I already wrote for the smaller sizes, put them underneath their parent media queries, and tweak the attributes based on the next screen size. 

I especially prefer it this way because the styles that are inside media queries usually depend on one another being present to make sense. This element becomes 30% wide at desktop size, this other element becomes 70% wide. I like having those two declarations next to each other in the code, because they happen at the same 'time', in both development, and in my re-sizing of the window.

I respect that others might feel differently. When I am working on another person's code and I see that their code follows the scattered-media-queries technique, I respect it, though I find it confusing and more time consuming to work in that mode for too long. "Oh, I have to tweak the width to 67% here, I guess I have to go find where that 30% is and tweak it up a few points, wherever it is."

I propose that we not try to standardize this. The rule should be to try not to mess with someone else's organizational scheme when you are collaborating, and to try to be consistent with your personal organizational scheme.

 Neither is 'bad' code, some people work faster in one way than in the other. They are just two different ways of handling the same problem.

**Comment by scampbell44** [comment]
"Neither is 'bad' code, some people work faster in one way than in the other. They are just two different ways of handling the same problem. "

Perfectly stated.

It's interesting reading your comments and gaining insight into your methods of process. I completely agree that each of our individual thought and development processes vary and there is no wrong way.

Personally,after getting the overall framework elements in place, I think and develop at a more elemental level and take a top down approach when developing a site. I develop the header on mobile and work my way up through breakpoints taking each element at a time. Then I progress the same way down the page.

**Comment by Brockenstein** [comment]
So the reason this is the suggested method is because it will make it easier for someone else who has to edit the code later. They can easily come to the sass find the nested element and make a change, they also can see exactly if they change they are making will affect any other screen sizes. Without needing to go and hunt and look.

With the fact that breakpoints mixin auto completes it shouldn't take any extra time to do this. I know it may be hard at first to change but I would suggest that you try it out a couple of times. It was hard for me to change images naming conventions to be descriptive instead of saying exactly where they would be placed but I have been trying it and I don't mind it as much and I understand the benefit it is for others.

**Comment by sbkates** [comment]
Why is it assumed that it's easier for collaborators one way or the other, since it's different from one person to the next? For me, it is harder to come in and make changes when things are grouped in this way. It feels _more_ like hunting and pecking with the recommended organization. 

It should be really clear to the newcomer which method is being used for that project. They can then stick with the method that's already being used.

**Comment by sylviakates** [comment]
It should be really clear to the newcomer which method is being used for that project. They can then stick with the method that's already being used.

**Comment by Mattferguson0422** [comment]
For me it is MUCH easier to see all changes an element makes within the element as opposed to having to scroll down and find the element in the section's breakpoint.  Especially with the way we have to search our SCSS document.  This also helps with readability in not getting too deep with our nesting as the standards state we should try and stay around 3 levels.

**Comment by jkmahoney** [comment]
The purpose for "nesting" or "grouping" your CSS/SASS/SCSS is for easier reading, writing, and finding  the media queries.

When you nest your media queries with the specific element that they belong with you don't have to search down your CSS document to find the different media queries and instances of that element in order to edit or update the styles. You can just scroll down a little or many times not even have to scroll to find all of the CSS/SASS that belongs to that element.

This is beneficial for both initial development, but this really comes in handy when making updates/edits to the code. Instead of someone who has never seen the CSS before having to scroll or search the page for all of the instances of the styles for a certain element, they will just be able to see the initial styles for that element and then all of the media queries/breakpoints associated with it right there close.

This makes your code simpler, cleaner, easier to read, and much easier for others and yourself to update/edit in the future.

The purposes of having a "standard" in place is so that all of our code looks similar, this way whoever gets our code to make an update or edit to doesn't have to guess at how we have programmed our site or what "style" we used, but can just go with what the "standard" is and what they have been using. This makes all of our sites easier for everyone to read and make edits and updates to. The updates are quicker and things go smoother.

We should always be striving to do things better, cleaner, quicker, more efficient, and in a way that we can all easily understand and work with. By doing things 3 or 4 different ways among ourselves we just end up with confusion and especially our maintenance team having to take more time to figure out how someone did something rather than just fixing the issue.

I think nesting all of our CSS/SASS/SCSS and media queries together with the elements they belong to is a great idea and the best way of coding for cleaner, simpler and easier to read and update code.

**Comment by michaelspellacy** [comment]
To nest media queries or not to nest media queries, that is the question. Big fan of the nest here from a maintenance perspective, but I agree it is a matter of preference and that no one way is the right way. We could (strongly) recommend that nesting be used if majority agrees to that, but it is not something I would personally call out in a code review as being wrong.

**Comment by Brockenstein** [comment]
I just want to make sure that we are clear. Its not about the right or wrong way. Because as long as it complies and works it technically works.

Being on such a large team that has grown and changes shape in the last couple of years we need to make sure we are being more consistent, So that way we know what to expect and sure it will be harder at first but some times doing something harder now makes it easier for someone else later. And that is truly appreciated in a team environment.

The reason the meeting was presented in the way it was is because the majority of the developers are doing things consistently but we have some inconsistencies we all need to work on. Myself included.

**Comment by sbkates** [comment]
If it's so strongly preferred by everyone else, I'll try to start my next
project that way. Too late for my current one though, ha.

**Comment by michaelspellacy** [comment]
"The purposes of having a "standard" in place is so that all of our code looks similar, this way whoever gets our code to make an update or edit to doesn't have to guess at how we have programmed our site or what "style" we used, but can just go with what the "standard" is and what they have been using. This makes all of our sites easier for everyone to read and make edits and updates to. The updates are quicker and things go smoother."

Yes, well said. Best reason to standardize on such things. I'm just saying, before there was Sass, there was grouping, which isn't wrong. In CSS, this is how it done and ONLY way to organize breakpoints.

**Comment by mianjohnson** [comment]
I will agree that there are several defaults within 2.0's SCSS structure that are helpful to modify for purposes of more efficient and navigable coding, but the reorganization of include brakpoint queries to their own separate level of structure is pretty ridiculous.

One of the best features of SCSS ove CSS is the ability for a more streamlined organization with the availability for nested statements in order to better identify and track similar styling blocks. 

Not taking into account of varying levels of screen sizes from principle development generally ends up making the process of having to go back and modify, typically, poorly written SASS/CSS considerably more difficult if these ideologies and a set of standards are not respected from one project to the next. When one of the biggest development problems that is seen tends to be the variations of unstandardized programming methods, this becomes a real issue for all that are involved.

Having a clear path of element mutation as defined by the parent/child relationships of elements is the most correct way that this can be expressed from an organizational standpoint and from a sense of just clear logic. The proper relationship to focus upon when markup is being modified is from the direct element reference itself first before how it is to be represented at any notated screen size.

Standardization of this practice is really the only way to make sure that everyone is clearly working on the same page when it regards best practices in coding structure and to ensure that we are all providing the best, organized product for our client base. To not take advantage of the parent/child structure that SCSS allows in integrating breakpoints within the hierarchy is, indeed, bad code and disrespectful to the intended nature of why the syntax is presented as such.

**Comment by sbkates** [comment]
Just to be clear, I wasn't suggesting the default 2.0 scss should be
changed.

**Comment by Brockenstein** [comment]
O the default SCSS should be changed though LOL. But that is neither here nor there is regards to the standards document. So if you want to talk about changes to the 2.0 system please jump on slack and bring up point.

So here is what I propose. Lets leave this topic open for several weeks. Give everyone a chance to try out nested breakpoints. And then come back and decide do we make it apart of the standards document or not.

**Comment by michaelspellacy** [comment]
All good guys and yes, agree, for sake of sanity on any project and future maintenance it probably would best to say that one way of doing it is preferred over another for those reasons. 

I really enjoy these discussions. :-)

**Comment by michaelspellacy** [comment]
That fine, Brock. 

Reminder: Whomever opens a topic is responsible for drafting the proposed  standard. As always, we can tweak and refine here until we have something we are all happy with to submit for inclusion.

**Comment by sbkates** [comment]
Proposed Standard:

For ease of collaboration, the preferred method of writing breakpoint-specific styles is to nest the breakpoint reference and style inside of the selector for the element, rather than outside of the selector for the element. The breakpoint should be written as a child of individual elements rather than as the parent of a group of elements.

**Comment by busby76** [comment]
I've got to say that the nested breakpoints are so much easier to manage than grouping media queries together in CSS. I hadn't used them until coming on the team and I wouldn't go back to doing it that way.

**Comment by scampbell44** [comment]
I concur with your proposed standard Sylvia. 

Now that almost a month has passed, i am curious. Have you had opportunity to alter your process? How did it go?

**Comment by sbkates** [comment]
I've switched to doing it entirely the way that was suggested by the group, and it is a little clearer to work with than the old way. Not a lot clearer, so I don't get some of the very strong feelings on how utterly superior a method it is, but I won't be going back to the old way. 

I end up writing all of the styles for an element at the same time now, rather than revising the whole page's worth of styles at different breakpoints as I was doing before. The code looks a little sloppier to me when reading it at first glance, but it's clear what's happening, due to the nesting.

**Comment by michaelspellacy** [comment]
Sweet. Just make sure not to go too crazy with nesting. More than 3 or 4 levels deep and you are asking for trouble in the form of a heavy CSS output!
